apiVersion: v1
kind: Service

metadata:
  name: login-service
  namespace: {{ .Values.namespace }}

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

spec:
  type: {{ .Values.loginApp.service.type }}

  selector:
    app: login-app

  ports:
    - name: http
      port: {{ .Values.loginApp.service.port }}
      targetPort: {{ .Values.loginApp.service.targetPort }}
      protocol: TCP
