apiVersion: v1
kind: Service

metadata:
  name: login-service
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.loginApp.service.type }}

  selector:
    app: login-app

  ports:
    - name: http
      port: {{ .Values.loginApp.service.port }}
      targetPort: {{ .Values.loginApp.service.targetPort }}
      protocol: TCP
