namespace: training

auth:
  sessionSecret: ""

postgres:
  image: postgres:16
  replicas: 1

  database: trainingdb
  username: admin
  password: Password@123

  storage:
    size: 20Gi
    storageClass: gp3

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

loginApp:
  replicas: 2

  image:
    repository: 797894062399.dkr.ecr.us-east-1.amazonaws.com/login-app
    tag: "cb63250cafe62a100a7a361a68e92c8ec43e31fc"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 5000

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

bmiApp:
  replicas: 2

  image:
    repository: 797894062399.dkr.ecr.us-east-1.amazonaws.com/bmi-service
    tag: "latest"
    pullPolicy: Always

  service:
    port: 80
    targetPort: 5001

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
