name: Deploy dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: dev
    secrets: inherit
