name: Build and Push Docker Image to Amazon ECR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: true
        default: "v1"

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 797894062399
  ECR_REPOSITORY: labevening-batch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          awsaccesskeyid: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awssecretaccesskey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.event.inputs.image_tag }} \
            ./login-app

      # Push Docker Image
      - name: Push Docker Image to ECR
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.event.inputs.image_tag }}

      # Display Image URI
      - name: Display Image URI
        run: |
          echo "Image pushed successfully."
          echo "Image URI:"
          echo "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.event.inputs.image_tag }}"
